name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.x', '14.x', '16.x']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn --frozen-lockfile

      - run: yarn run lint

      - run: yarn run test --coverage
